//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matching_cs.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMContext : DbContext, IDisposable
    {
        public FMContext()
            : base("name=FMContext")
        {
        }
    
        
    
        public virtual DbSet<tbBiometria> tbBiometria { get; set; }
    }
}
