//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matching_cs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBiometria_Akiama
    {
        public int id { get; set; }
        public byte[] biometriaBytes { get; set; }
        public byte[] templateImage { get; set; }
    }
}
